//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyImageMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public string CustID { get; set; }
        public string CardTypeID { get; set; }
        public string CardID { get; set; }
        public string CardHolder { get; set; }
        public string CardNumber { get; set; }
        public string CardExp { get; set; }
        public string CardCVV { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual CardType CardType { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
