//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyImageMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public string ImgID { get; set; }
        public string CartID { get; set; }
        public string CartItem { get; set; }
        public int CartQty { get; set; }
        public System.DateTime CartDate { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Image Image { get; set; }
    }
}
