//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyImageMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustRole
    {
        public int ID { get; set; }
        public string CustID { get; set; }
        public string RoleID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Role Role { get; set; }
    }
}
