//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyImageMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Images = new HashSet<Image>();
        }
    
        public string OrderStatusID { get; set; }
        public string InvoiceID { get; set; }
        public string PayMethodID { get; set; }
        public string CustID { get; set; }
        public string OrderID { get; set; }
        public string OrderItem { get; set; }
        public int OrderQty { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
