//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyImageMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricePrintSize
    {
        public int PricePrintSizeID { get; set; }
        public string PriceID { get; set; }
        public string PrintSizeID { get; set; }
    
        public virtual Price Price { get; set; }
        public virtual PrintSize PrintSize { get; set; }
    }
}
