//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyImageMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public string StoreID { get; set; }
        public string StoreName { get; set; }
        public string StoreAddr { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
